version = '2'

[linters]
default = 'none'
enable = [
  'errname',
  'errorlint',
  'govet',
  'importas',
  'ineffassign',
  'sloglint',
  'staticcheck',
  'whitespace'
]

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[formatters]
enable = [
  'gofmt'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
